### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by masylum** [masylum/mongolia#14]
In order to save disk space, sometimes people need to name their fields with obscure names.
I think its a good idea to let users define alias for their field names.

```
MODEL.alias = {
  created_at: 'ca',
  name: 'n'
};

foo.mongo('findOne', {name: 'bar'}, function (err, doc) {
  console.log(doc.name); // => 'bar'
  console.log(doc.created_at); // => 'Jun 12, 2011 ...'
  console.log(doc.n); // => 'bar'
});
```

This feature if used will add a little overhead to setup the setters/getters on returning elements.

**Comment by trollixx** [comment]
Maybe it's better do not allow access by alias and field name at the same time?

**Comment by masylum** [comment]
I have to think a little bit more about this feature. I don´t want to complicate too much the source.
