### ISSUE TITLE
Allow fire and forget operations

### ISSUE THREAD

**Issue by masylum** [masylum/mongolia#8]
Update, insert, findAndModify, updateEmbeddedDocument, pushEmbeddedDocument ... Make callbacks optional

**Comment by txus** [comment]
This could be nice.

**Comment by masylum** [comment]
then do it. I can't assign the task :(

**Comment by txus** [comment]
Done in acf92add41f314fefd01d402e6a5a009ccec7e17 and fe33b9351e770dc9493779c67d65a0c922e9b04b
